---
title: "Case studies"
page-layout: article
format:
  html:
    toc: true
    collapse-level: 4
---

The WaterSmart Dams project is a collaborative initiative to improve the resilience and performance of farm dams in Western Australia. The latest Water Smart Dams case studies showcase key findings and technologies trialled across the project, including:

## <a href="https://github.com/Water-Evaluation-Platform/wep-docs/raw/main/pdfs/Benchmarking evaporation.pdf" target="_blank">Benchmarking evaporation</a>

As part of the project, a benchmarking study evaluated evaporation and leakage losses at two sites: Duranillin and Hines Hill using real-time weather and water level monitoring with the General Lake Model (GLM). The aim was to better understand water loss from unmodified farm dams to guide future dam designs and improve water security for growers.

## <a href="https://github.com/Water-Evaluation-Platform/wep-docs/raw/main/pdfs/Dam covers.pdf" target="_blank">Dam covers</a>

This trial examined the use of floating dam covers, deployed at full scale to evaluate real-world effectiveness in reducing evaporation losses. With two demonstration sites in Western Australia’s south-west, the project aimed to evaluate the actual effectiveness of the floating cover design, livestock compatibility, and ease of installation to assess if they may contribute to drought resilience and farm water security.

## <a href="https://github.com/Water-Evaluation-Platform/wep-docs/raw/main/pdfs/Enhanced catchments.pdf" target="_blank">Enhanced catchments</a>

Five demonstration sites across south-west WA trialled different catchment surface treatments from roaded earthworks to repurposed PVC and HDPE tarpaulins. These enhancements targeted a persistent challenge in Australian agriculture: capturing runoff from small, often-overlooked rainfall events. The trials aimed to explore how surface modification technologies can help farmers improve water resilience in a drying climate.

## <a href="https://github.com/Water-Evaluation-Platform/wep-docs/raw/main/pdfs/Vegetated Dam.pdf" target="_blank">Vegetated dams</a>

On their mixed farming property near Boscabel in Western Australia's Shire of Kojonup, Brad and Sarah Ashton manage an 8.2 ML dam, that has surrounding native vegetation including sheoaks and paperbarks. As part of the WaterSmart Dams project, this trial evaluated how this natural solution helps water security and drought resilience. The farm-scale water management trial evaluated how vegetation at the site reduces wind turbulence across the dam, thereby lowering evaporation and saving water.

## <a href="https://github.com/Water-Evaluation-Platform/wep-docs/raw/main/pdfs/Sub-surface drain.pdf" target="_blank">Sub-surface drains</a>

Three growers across WA’s south-west Wheatbelt trialled sub-surface drainage systems to investigate whether paddock waterlogging can be turned into a valuable water resource. Field trials measured both the quantity and quality (salinity) of water to evaluate if this is an option to enhance or supplement runoff into dams. From DIY trenching to contractor-installed designs, the growers hosted and evaluated sub-surface drainage options and tested them in real-world conditions across multiple seasons.