---
title: "Technical reports"
page-layout: article
format:
  html:
    toc: true
    collapse-level: 4
---

The WaterSmart Dams project is a collaborative initiative to improve the resilience and performance of farm dams in Western Australia. Detailed findings from the Water Smart Dams projects can be found in the following technical reports:

**<a href="https://storage.googleapis.com/wsd-reports/WSD%20Evaporation%20Technical%20Report.pdf" target="_blank">WSD Evaporation Technical Report</a>**

*This technical report investigates the extent and drivers of water losses from farm dams in Western Australia (WA), with a specific focus on evaporation and leakage. Using high-resolution simulations from the General Lake Model (GLM), the study benchmarks daily water losses across multiple case study dams and evaluates the effectiveness of common mitigation strategies, including quantifying the evaporation reduction from continuous floating covers and fringing vegetation.*

***

**<a href="https://storage.googleapis.com/wsd-reports/WSD%20Surface%20Water%20Technical%20Report.pdf" target="_blank">WSD Surface Water Technical Report</a>**


*When on-farm sources are exhausted, relying on water carting from scheme water and other supplementary supplies is the single most costly way to source water. It is a poor and costly response to drought adaptation. This project looks at options to address this challenge by: 1) evaluating the performance of enhanced or engineered surface catchments that use PVC tarpaulins and other plastic surfaces (HDPE) to harvest water from low-intensity rainfall events, and 2) the utility of subsurface drainage systems to capture water from waterlogged soils and harvest and store it in dams for on-farm non-potable use.*