---
title: "Profiles"
page-layout: article
format:
  html:
    toc: true
    collapse-level: 4
---

## Catchment profiles

Depending on how you configure the catchment profile, there are various ways that you can model catchments and simulate runoff from them after precipitation events.

For each simulation, you can configure two catchments mix models used to generate runoff from catchments. For example, you could set catchment 1 to be a small roaded catchment using a runoff threshold-style catchment model and you could set catchment 2 to be a larger vegetated catchment where your catchment model accounts for evapotranspiration losses.

### Runoff threshold-style catchments

Runoff threshold-style models daily runoff from the catchment if rainfall exceeded a runoff threshold, all rainfall above the threshold runs into the dam.

To use runoff threshold-style catchments you can set the depth to the confining layer to 0 (this effectively prevents the catchment from storing moisture) and set an appropriate runoff threshold. You can optionally set a runoff coefficient where a percentage of precipitation exceeding the runoff threshold actually runs off into the dam. 

::: {.callout-tip}
## Modelling runoff from a plastic catchment

You would like to model runoff from a catchment that you have covered in plastic sheeting. You know the plastic covered catchment generates runoff for precipitation events greater than 1 mm and 80% of precipitation greater than 1 mm runs off into the dam.

This is how you would configure this catchment profile:

```{=html}
<div class="video-container">
    <iframe class="responsive-iframe" src="https://drive.google.com/file/d/1W8poKvqSh8DCuEtcWNCwc2qQ_BKdfla5/preview" allow="autoplay"></iframe>
</div>
```
:::

### Evaporation from bare earth catchments

It is possible to simulate runoff from bare earth catchments that store soil moisture and retain memory of soil moisture levels. Here, the evaporating bare earth catchments are based on a model by <a href="https://ascelibrary.org/doi/abs/10.1061/(ASCE)0733-9437(2005)131:1(14)" target="blank">Allen et al. (2005)</a>, which is a two-stage model. 

The first stage of the model is when evaporation is energy limited and the soil provides enough moisture to meet evaporative demand. There is a constant amount evaporation between field capacity and a point where all readily available water has been evaporated. 

The second stage of the model is soil limited, where soil hydraulic properties and conditions limit the amount of moisture that can be moved to the surface for evaporation. The rate of evaporation from the soil linearly decreases with soil moisture to a point where no more soil moisture can be evaporated (half the wilting point, following <a href="https://ascelibrary.org/doi/abs/10.1061/(ASCE)0733-9437(2005)131:1(14)" target="blank">Allen et al. (2005)</a>). You can set the depth and porosity of the soil to determine how much moisture the catchment can store. Any precipitation events that exceed the catchment’s storage capacity and infiltration capacity will runoff.

:::{.callout-note}
## Parameter definitions for bare earth catchments

You can obtain these parameters from the literature, from geospatial soil properties products or via estimation using pedotransfer functions.

* **Soil depth to confining layer (m):** The depth of soil available to store moisture.
* **Porosity (%):** The percentage of the soil volume comprising pores.
* **Field capacity (%):** The maximum amount of water the soil can hold after drainage.
* **Readily evaporable water (%):** The point where evaporation from the soil stops being energy limited (soil moisture units %).
* **Wilting point (%):** Level of soil moisture where plants cannot extract water (soil moisture units %).
* **Hygroscopic point (%):** Level of soil moisture where there is no more evaporation. Set this to `0`. The hygroscopic point is estimated as half the wilting point.
* **Initial soil moisture (%):** The initial soil moisture at the start of a simulation.
* **Infiltration capacity / runoff threshold (mm / timestep):** The maximum rate at which water can enter the soil (mm / timestep). Any rainfall above this amount is available for runoff.
* **Runoff coefficient (%):** Of the water available for runoff (i.e. exceeding the runoff threshold), the percentage that actually runs.
* **Vegetated catchment:** Set this to `False` to ensure no transpiration is considered an the bare earth evaporation model from [Allen et al. (2005)](https://ascelibrary.org/doi/abs/10.1061/(ASCE)0733-9437(2005)131:1(14)) is used.
:::

### Evaporation from vegetated catchments

To simulate runoff from vegetated catchments an adaptation of a model by <a href="https://www.sciencedirect.com/science/article/abs/pii/S0309170801000057" target="_blank">Laio et al. (2001)</a> is used. Precipitation events that exceed the catchment’s storage capacity determined by porosity, current soil moisture levels and infiltration capacity will yield runoff. 

The current soil moisture of the vegetated catchment is estimated through considering evapotranspiration losses and the history of precipitation events. Evapotranspiration losses are modelled in stages. 

The first stage occurs when soil moisture is abundant and evapotranspiration occurs at the maximum rate permitted given plant types and the prevailing weather. This stage persists until soil moisture reaches the refill point. 

During the second stage evapotranspiration is plant and soil limited, controlled by both soil properties and plants reducing transpiration. Between the refill point and the wilting point, evapotranspiration decreases linearly with soil moisture.
                    
Below the wilting point, small evaporative losses occur until the hygroscopic point is reached.

When soil moisture reaches the hygroscopic point, there is no evaporation from the catchment.

:::{.callout-note}
## Parameter definitions for vegetated catchments

You can obtain these parameters from the literature, from geospatial soil properties products or via estimation using pedotransfer functions.

* **Soil depth to confining layer (m):** The depth of soil available to store moisture.
* **Porosity (%):** The percentage of the soil volume comprising pores.
* **Field capacity (%):** The maximum amount of water the soil can hold after drainage.
* **Refill point (%):** The point where plants have used up all readily available water for transpiration (soil moisture units %).
* **Wilting point (%):** Level of soil moisture where plants cannot extract water and transpiration losses cease (soil moisture units %).
* **Hygroscopic point (%):** Level of soil moisture where there is no more evaporation.
* **Initial soil moisture (%):** The initial soil moisture at the start of a simulation.
* **Infiltration capacity / runoff threshold (mm / timestep):** The maximum rate at which water can enter the soil (mm / timestep). Any rainfall above this amount is available for runoff.
* **Runoff coefficient (%):** Of the water available for runoff (i.e. exceeding the runoff threshold), the percentage that actually runs.
* **Vegetated catchment:** Set this to `True` to consider transpiration losses and use the evatranspiration model from Laio et al. (2001) is used.
:::

## Dam profiles

Under the *Settings* tab in the navbar, you can create dam profiles. A dam profile is a representation of water extraction from the dam considering daily livestock drinking, spray uses, irrigation and other dam water uses. 

The dam profile is attached to a dam simulation and is used to estimate the daily demand for water placed on the dam and to remove this water each day.

::: {.callout-tip}
## Modelling runoff from a plastic catchment

You have a dam which 150 sheep use for drinking water and for three months of the year you use the dam's water for your spray program.

This is how you would create this dam profile:

```{=html}
<div class="video-container">
    <iframe class="responsive-iframe" src="https://drive.google.com/file/d/1-P_7V4RjPBtEOHLFDN7C1wxPvqve9UhB/preview" allow="autoplay"></iframe>
</div>
```
:::

You can view and delete dam profiles in your *Accounts* page.

### Dam water demand

Use the tabular form to specify the water demand placed on the dam.

There are options to set the number of sheep, pigs and cattle that depend upon the dam each month. The livestock's daily drinking rate is computed based on daily maximum temperatures, obtained from SILO, and the proportion of sheep, pigs and cattle that comprise the stock.

To configure irrigation demand, set the monthly amount of water the dam needs to provide for irrigation purposes in kL. 

To configure spray programs, set the spray rate in litres per hectare, the area sprayed and the number of sprays per month. 

There are also options for you to input other uses which the dam must provide water for; these are set as monthly amounts in kL.

### Additional water supplies

If you have additional water supplies, you can capture this within your dam profile and this supply is discounted from the amount the dam must provide to meet demand. 

There are options to configure monthly supply from bores or other sources in kL.

## Cost profiles

Under the *Settings* tab in the navbar, you can create cost profiles. You can view and delete cost profiles in your *Accounts* page.

A cost profile specifies the costs to build and maintain a dam and catchment. Cost profiles are attached to dam simulations to provide an indication of the costs associated with constructing and building a dam and catchment combination.

The cost profiles are also used in design and comparative analyses; for example, the dam design mode seeks to find the cheapest dam to construct that will be reliable for a given dam profile (demand) and existing catchment. The leaky dam and evaporation reduction analysis modes use the cost profile to assess the cost-benefit of fixing a leaky dam or using evaporation suppression devices (e.g. covers). You would use the cost profile to capture different strategies for fixing leaky dams or reducing evaporation, the different strategies would be reflected in the values attached to the cost profile.

Default values are provided based on DPIRD's report on the *Options for Farm Water Supply in a Volatile, Drying Climate*. However, it is recommended that you create custom cost profiles to more accurately reflect your situation.

:::{.callout-note}
## Parameter definitions for costs profiles

* **Costs profile name:** A descriptive name for your cost profile.
* **Catchment 1 construction costs ($ / ha):** Upfront costs to construct catchment 1.
* **Catchment 1 years of operation:** The number of years catchment 1 will be operational.
* **Catchment 1 maintenance multiplier ($ / ha):** The annual cost of maintaining catchment 1.
* **Catchment 2 construction costs ($ / ha):** Upfront costs to construct catchment 2.
* **Catchment 2 years of operation:** The number of years catchment 2 will be operational.
* **Catchment 2 maintenance multiplier ($ / ha):** The annual cost of maintaining catchment 2.
* **Silt trap and piped inlet costs ($):** Upfront costs to build a silt trap and piped inlet.
* **Dam construction costs ($ / m³):** Upfront costs to construct the dam.
* **Dam site drilling costs ($):** Upfront costs for dam site drilling.
* **Cost to line dam ($ / m²):** Costs to line dams to fix leaks.
* **Evaporation treatment cover cost ($ / m²):** Costs to cover dams to reduce evaporative losses.
* **Interest rate (%):** Interest rate to compute annual repayments for construction costs.
:::